### ISSUE TITLE
Channel.json을 분리하신 이유가 궁금합니다.

### ISSUE THREAD

**Issue by wiserain** [wonipapa/Channel.json#1]
운영상 특별한 이점이나 생각하고 계신 방식이 있는지 궁금합니다. 이 버전이 언제나 우선인건지? 아니면 백업 repository인건지? 어떤 시점에서 어느쪽이 우선하는 것인지 더 애매모해지는 것 같기도 하거든요.

p.s. xlsx도 분리하면 더 일관성 있지 않을까요? 조심스런 생각입니다.

**Comment by wonipapa** [comment]
epg2xml은 버전업이 없는데 차널 소스를 변경해야할
떼가 종종 있더군요. 그때마다 버전업은 할 수없고 해서 따로 분리를 해보면 어떨까 생각해서입니다.채널 업데이트는 똑같이 갈생각입니다.
xlsx는 제가 편의상 만들어 놓은 파일이라서 업데이트가 잘 안되서 새 리포지터리에 넣지 않았습니다. 아예 빼버릴까 생각중입니다. 보통 엑셀파일은 대규모 업데이트시만 백업의 의미로 반영하게 되더라구요.
