### ISSUE TITLE
1.2.3 p3 버전.

### ISSUE THREAD

**Issue by wlwhfhs** [wonipapa/Channel.json#3]
수정해 주셔서 감사합니다.
sk 기준 제대로 편성정보를 가져오고 있는것 같습니다.
단, Lifetime---->라이프타임 sk 채널 213번 누락 되어 있으니 참고하세요. 
Channel.json 파일에 직접 213번 적어넣으니 잘 작동합니다.

늘 행복하세요!!

**Comment by wonipapa** [comment]
수정했습니다.
