### ISSUE TITLE
현재 POOQ 소스 정보.

### ISSUE THREAD

**Issue by wlwhfhs** [wonipapa/Channel.json#4]
현재 소스 정보가 POOQ으로 설정된 채널들이 안됩니다.

**Comment by wonipapa** [comment]
확인해보겠습니다. Pooq 소스가 문제가 좀 있는 것 같습니다.

**Comment by wlwhfhs** [comment]
@wonipapa 위 내용은 예전 12월 1.2.3? 나오기전 글입니다. 
이미 해결된 후 코멘트를 어떻게 삭제하는지 몰라 놔두었는데 이제야 보셨네요. 
늘 잘 사용하고 있고 타인을 위해 애써 주셔서 감사합니다!!
