### ISSUE TITLE
채널 정보 업데이트 부탁드려봅니다.

### ISSUE THREAD

**Issue by kumkumi** [wonipapa/Channel.json#5]
U+ 채널 정보가 좀 바뀌었습니다.

1.
플레이보이 190번  -> 290번
미드나잇    191번  -> 291번
비키           192번  -> 292번
허니TV      193번  -> 293번
성인 채널이 이렇게 바뀌었고,

2.
158번 키즈톡톡 이라는 채널이 키즈톡톡 플러스로 바뀌었습니다. 
채널번호는 그대로인데 채널명과 EPG 소스가 안 맞습니다.

3. 
EBS u 채널명이 EBS kids 로 바뀌었습니다.
이건 방송사에서 바꾼 거라 3사 동일인 거 같습니다.
EPG는 기존 EBS u 로 잘 받아와서 채널명만 변경해서 사용중입니다.

4.
jtbc2 epg가 나오지 않습니다.

5.
아리랑tv epg가 있기는 한데 
당일이 아니라 다음날 epg부터 불러와져서 epg 정보가 없는 것처럼 나옵니다.
가령 오늘이 1월2일이면, epg  정보는 1월3일부터 나옵니다.

항상 감사드립니다!

**Comment by wonipapa** [comment]
1,3 번은 바로 고칠 수 있을 것 같습니다.
3, 4번은 확인해보겠습니다.
5번은 프로그램 자체를 ISCS 소스가 문제가 있어서 그렇습니다.

**Comment by wonipapa** [comment]
수정 완료
