### ISSUE TITLE
감사합니다!

### ISSUE THREAD

**Issue by wlwhfhs** [wonipapa/Channel.json#6]
금일 새롭게 올리신 2018년 2월 1일 Channel.json 적용하니 그전 ISCS 소스문제로 안나오던 채널 해결되었네요.
SK 기준. 채널 1개 빼고는 전부 잘 나오는 상태고 안나오는 채널은 "Id": 56, "Name": "EBS English" 입니다.

늘 잘 사용하고 있고 타인을 위해 애써 주셔서 감사합니다!!

**Comment by wonipapa** [comment]
확인해보겠습니다.
