### ISSUE TITLE
한번 더 요청드립니다.

### ISSUE THREAD

**Issue by kumkumi** [wonipapa/Channel.json#7]
며칠전에 몇 가지 요청드렸는데,
해결됐다는 이메일을 받고 확실하게 확인해보려고 다시 설치해봤습니다.
키즈톡톡 플러스 채널의 EPG가 안 맞네요.
U+홈페이지에서 편성표를 확인해보니까 지금 키즈톡톡이랑 키즈톡톡플러스가 모두 있는데,
현재  Channel.json에서는 키즈톡톡으로 연결이 되어 있는 거 같습니다.
보니까 서비스ID가 805번이 키즈톡톡인 거 같고요...
키즈톡톡 플러스는 790번 같은데 제가 초보라 자세히 몰라서 확실히 말씀을 못드리겠네요ㅜ.ㅜ
JTBC2는 이제 잘 나옵니다.
키즈톡톡 플러스 확인 좀 부탁드릴게요^^;
감사합니다!

**Comment by wonipapa** [comment]
LG 편성표에 키즈톡톡과 키즈톡톡 플러스 두개가 있어서 바꾼 건데 틀린가 보네요.
네이버 편성표가 맞다면 그걸로 바꾸도록 하겠습니다.
제가 LG를 쓰지 않아서 확인이 불가능하거든요.
급하시면 소스는 NAVER  815316으로 하시면 됩니다.

**Comment by kumkumi** [comment]
앗..댓글을 다셨군요.
제가 본문을 수정했는데 급한대로 네이버로 써보겠습니다^^;
감사합니다^^
혹시 기프티콘 같은 거 보내드릴 수 있는 방법은 없나요?
매번 도움만 받는 거 같아서 커피라도 하나 보내드리고 싶습니다.

**Comment by wonipapa** [comment]
수정했습니다.

**Comment by kumkumi** [comment]
본문을 수정했는데  벌써 댓글을 다셨군요~
네이버로 고쳐서 해보니 잘 맞습니다.
감사합니다^^;
매번 도움 주셔서 커피 기프티콘 같은 거라도 보내드리고 싶은데 어떻게 하면 될까요?

**Comment by wonipapa** [comment]
https://www.facebook.com/chericface/
이거 좋아요 눌러주시면 작은 후원이 됩니다. 제가 아는 분이 운영하는 곳인데 평가사항에 이런 것도 있어서요.
